version: '1.0.0'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - copper-network

  copper-ai:
    container_name: copper-ai
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./pages/api/auth/google.api.local.json      
    networks:
      - copper-network

volumes:
  mongo-data:

networks:
  copper-network:
    driver: bridge
