version: '1.0.0'

services:
  copper-ai:
    container_name: copper-ai
    build: .
    ports:
      - '3000:3000'
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./pages/api/auth/google.api.local.json      
    networks:
      - copper-network

networks:
  copper-network:
    driver: bridge
