version: '1.0.0'

services:
  copper-ai:
    container_name: copper-ai
    build: .
    ports:
      - '3000:3000'      
    networks:
      - copper-network

networks:
  copper-network:
    driver: bridge
